modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"
[[mods]]
modId="happytrails"
version="${file.jarVersion}"
displayName="Happy Trails Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/happy-trails"
logoFile="HappyTrailsForgeMod.png"
authors="MacTso, Lupicus"
description='''Happy Trails Mod.'''
[[dependencies.happytrails]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.happytrails]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="SERVER"
