modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
[[mods]]
modId="happytrails"
version="${file.jarVersion}"
displayName="Happy Trails Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/happy-trails"
updateJSONURL="https://github.com/mactso/happytrails/raw/main/update.json"

logoFile="HappyTrailsForgeMod.png"
authors="MacTso, Lupicus"
description='''Happy Trails Mod.'''
[[dependencies.happytrails]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.happytrails]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18.0)"
    ordering="NONE"
    side="SERVER"
