modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="ht"
version="${file.jarVersion}"
displayName="Happy Trails Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/happy-trails"
logoFile="HappyTrailsForgeMod.png"
authors="MacTso, Lupicus"
description='''Happy Trails Mod.'''
[[dependencies.ht]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.ht]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="SERVER"
